### ISSUE TITLE
module 'lfs' not found

### ISSUE THREAD

**Issue by mediter** [lvzixun/dump_ios_backup#2]
```
lua: dump_backup.lua:7: module 'lfs' not found:
	no field package.preload['lfs']
	no file '/usr/local/share/lua/5.3/lfs.lua'
	no file '/usr/local/share/lua/5.3/lfs/init.lua'
	no file '/usr/local/lib/lua/5.3/lfs.lua'
	no file '/usr/local/lib/lua/5.3/lfs/init.lua'
	no file './lfs.lua'
	no file './lfs/init.lua'
	no file '/usr/local/lib/lua/5.3/lfs.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lfs.so'
stack traceback:
	[C]: in function 'require'
	dump_backup.lua:7: in main chunk
	[C]: in ?
```

**Comment by mediter** [comment]
dump_backup requires Lua with LuaFileSystem.

on macOS, the convenient way to install these two is as follows:

```
brew install luarocks

luarocks install luafilesystem
```

**Comment by EZRAIDv2** [comment]
> dump_backup requires Lua with LuaFileSystem.
> 
> on macOS, the convenient way to install these two is as follows:
> 
> ```
> brew install luarocks
> 
> luarocks install luafilesystem
> ```

After installing luarocks (`sudo apt install luarocks`) this returns '**lua.h**`: No such file or directory`'
